version: 2

# Use this if you are referencing modules from a private module registry.
# registries:
#   hcp-terraform:
#     type: terraform-registry
#     url: https://app.terraform.io
#     token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
#
# If you add the private module registry configuration above, you must add
# the `registries: '*'` configuration under the `terraform`
# package-ecosystem configuration below.

updates:
  - package-ecosystem: terraform
    directories:
      - examples/**/*
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(docs)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(ci)
