formatter: markdown table

recursive:
  enabled: false

content: |-
  ## Usage

  ### main.tf
  ```hcl
  {{ include "examples/imports/main.tf" }}
  ```

  ### imports.tf
  ```hcl
  {{ include "examples/imports/imports.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Resources }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject

settings:
  lockfile: false
