name: Lint

on: pull_request

permissions:
  contents: read

jobs:
  actionlint:
    name: GitHub Actions
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint Workflow Files
        uses: craigsloggett/lint-github-actions-workflows@e35be5a4bc8d07dd4e9e7410f26205820ae0e064 # v1.0.3

  yamllint:
    name: YAML
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint YAML Files
        uses: craigsloggett/lint-yaml@40a90b91b0d3ac513cc98e8665ef332188b76176 # v1.0.12

  terraform:
    name: Terraform
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint Terraform Configuration
        uses: craigsloggett/lint-terraform@3daac56965ea83cb148e57151facbaed4fbecd7e # v1.1.0

  terraform-docs:
    name: Terraform Docs
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint Terraform Module Documentation
        uses: craigsloggett/lint-terraform-docs@fe49ca917fb95b3097a07cca0dab87f7517ce6bf # v1.0.12
