name: Lint

on: pull_request

permissions:
  contents: read

jobs:
  actionlint:
    name: GitHub Actions
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint Workflow Files
        uses: craigsloggett/lint-github-actions-workflows@bf90c927b04eeaffc4cc111083e351de7582b91e # v1.0.2

  yamllint:
    name: YAML
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint YAML Files
        uses: craigsloggett/lint-yaml@8b54828bcc0973caa0c43216ceef797ea8bdab54 # v1.0.3

  terraform:
    name: Terraform
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint Terraform Configuration
        uses: craigsloggett/lint-terraform@f13ab166dd27504d697862edcc1e7821fae52a64 # v1.0.8

  terraform-docs:
    name: Terraform Docs
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint Terraform Module Documentation
        uses: craigsloggett/lint-terraform-docs@60e2ce09ea812bf2e24a6a8c20efc1c54110db1d # v1.0.6
