name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: GitHub
    runs-on: ubuntu-24.04

    outputs:
      new-release-published: ${{ steps.release.outputs.new-release-published }}
      new-release-version: ${{ steps.release.outputs.new-release-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Create a GitHub Release
        id: release
        uses: craigsloggett/create-github-release@ca381e65d8d9bc17c1ce58c4bd8c54d8381d064b # v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
